import React from 'react';
import {CopyToClipboard} from 'react-copy-to-clipboard';
import ReactWindowResizeListener from 'window-resize-listener-react';
import {
	Step,
	Stepper,
	StepLabel,
	StepContent,
} from 'material-ui/Stepper';
import ExpandTransition from 'material-ui/internal/ExpandTransition';
import FlatButton from 'material-ui/FlatButton';
import RaisedButton from 'material-ui/RaisedButton';
import EntropyInput from './EntropyInput';
import QRCodeBox from './QRCodeBox';

/**
 * @description	The Register page component
 * @constructor
 * @param {Object} props - The props that were defined by the caller of this component.
 */
class Register extends React.Component {

	constructor(props){
		super(props);

		/**
		 * @typedef {Object} ComponentState
		 * @property {boolean} loading - Indicates whether the stepper component is loading.
		 * @property {number} stepIndex - The index of the stepper.
		 * @property {string} accountKey - The private key that generates the account address.
		 * @property {string} accountAddress - The address of the account.
		 * @property {string} stepperOrientation - Indicates whether the stepper is horizontal or vertical.
		 */

		/** @type {ComponentState} */
		this.state = {
			loading: false,
			stepIndex: 0,
			accountKey: '',
			accountAddress: '',
			stepperOrientation: 'vertical',
		};
	}

	/**
	 * @description Lifecycle event handler called just after the App loads into the DOM.
	 * Check the screen width to decide if stepper should be vertical or horizontal.
	 */
	componentWillMount(){
		this.setState({stepperOrientation: ((innerWidth < 570) ? 'vertical':'horizontal') });
	}

	/**
	 * @description Handle next step of the stepper.
	 */
	handleNext = () => {
		const {stepIndex} = this.state;

		// Account Creation Finished
		if (stepIndex >= 2){
			this.props.onComplete(this.state.accountAddress, this.props.history);
		}
		if (!this.state.loading) {
			this.dummyAsync(() => this.setState({
				loading: false,
				stepIndex: stepIndex + 1,
			}));
		}
	};

	/**
	 * @description Handle previous step of the stepper.
	 */
	handlePrev = () => {
		const {stepIndex} = this.state;
		if (!this.state.loading) {
			this.dummyAsync(() => this.setState({
				loading: false,
				stepIndex: stepIndex - 1,
			}));
		}
	};

	/**
	 * @description Execute when the Entropy input is complete. The parameter is an object with the account address and
	 * the WIF key.
	 * @see {@link https://en.bitcoin.it/wiki/Wallet_import_format}
	 * @param {object} accountData - The object with the wif and address keys generated by entropy input.
	 */
	handleEntropyComplete = (accountData) => {
		this.setState({accountKey: accountData.wif, accountAddress: accountData.address},function stateUpdateComplete() {
			this.handleNext();
		}.bind(this));
	};

	/**
	 * @description Async callback for stepper transitions.
	 * @param {function} cb - The callback that should be executed after 500ms.
	 */
	dummyAsync = (cb) => {
		this.setState({loading: true}, () => {
			this.asyncTimer = setTimeout(cb, 500);
		});
	};

	/**
	 * @description Set the stepper orientation state based on the the viewport width.
	 */
	checkStepper = () => {
		this.setState({stepperOrientation: ((innerWidth < 570) ? 'vertical':'horizontal') });
	};

	/**
	 * @description Resize handler that runs anytime the width/height change.
	 */
	resizeHandler = () => {
		this.checkStepper();
	};

	/**
	 * @description Render the step content based on index.
	 * @param {number} stepIndex - The index of the stepper.
	 */
	getStepContent(stepIndex) {
		switch (stepIndex) {
			case 0:
				return (
					<div>
						<p className="app-register-text">To create your account move the cursor randomly inside box
							bellow for a while, until
							it is completely green</p>
						<div>
							<EntropyInput onComplete={this.handleEntropyComplete}/>
						</div>
					</div>
				);
			case 1:
				return (
					<div style={{textAlign: 'center'}}>
						<p className="app-register-text">Please Download and Save this QR code that contains the access
							key or copy the key from the box
							it before proceed.</p>
						<p className="app-register-text">This Access Key is the only login credential you need.</p>
						<div>
							<QRCodeBox value={this.state.accountKey}/>
						</div>
						<p className="app-register-text">You can also Copy/Paste the key somewhere or send it to your
							email</p>
						<div className="account-backup">
							<div className="account-address">{this.state.accountKey}</div>
							<CopyToClipboard text={this.state.accountKey}>
								<RaisedButton style={{margin: 12}} label="Copy to clipboard"/>
							</CopyToClipboard>
							<RaisedButton
								style={{margin: 12}}
								href={
						"mailto:?subject=MyReads%20Account%20Credentials&body=This is your access key for MyReads: " +
								this.state.accountKey}
								label="Send to your email"/>
						</div>
						<p className="account-note">Note: If you lost this key will not be able to recover your
							account.</p>
					</div>
				);
			case 2:
				return (
					<div style={{textAlign: 'center'}}>
						<p className="account-congratulations">Congratulations!</p>
						<p className="app-register-text">
							If you already saved your access key feel free to continue.</p>
						<p className="app-register-text">I hope you enjoy the app!</p>
					</div>
				);
			default:
				return 'You\'re a long way from home sonny jim!';
		}
	}

	/**
	 * @description Render the step actions (buttons) based on index.
	 * @param {number} stepIndex - The index of the stepper.
	 */
	renderStepActions(stepIndex) {
		return (
			<div style={{marginTop: 24, marginBottom: 12}}>
				{/* Show stepper control only after the first step */}
				{(stepIndex >= 1) &&
				<div style={{textAlign: 'center'}}>
					<FlatButton
						label="Back"
						disabled={stepIndex === 0}
						onClick={this.handlePrev}
						style={{marginRight: 12}}
					/>
					<RaisedButton
						label={stepIndex === 2 ? 'Finish' : 'Next'}
						primary={true}
						onClick={this.handleNext}
					/>
				</div>
				}
			</div>
		);
	}

	/**
	 * @description Render the actions and content for the horizontal stepper.
	 */
	renderHorizontalContent() {
		const {stepIndex} = this.state;
		const contentStyle = {margin: '0 16px', overflow: 'hidden'};

		return (
			<div style={contentStyle}>
				<div>{this.getStepContent(stepIndex)}</div>
				{this.renderStepActions(stepIndex)}
			</div>
		);
	}

	render() {
		const {loading, stepIndex} = this.state;

		return (
			<div>
				<ReactWindowResizeListener onResize={this.resizeHandler}/>

				<div style={{width: '100%', maxWidth: 1200, margin: 'auto'}}>

					{(this.state.stepperOrientation === 'horizontal') &&
					<div>
						<Stepper activeStep={stepIndex}>
							<Step>
								<StepLabel>Swipe to create account</StepLabel>
							</Step>
							<Step>
								<StepLabel>Save the Access Key</StepLabel>
							</Step>
							<Step>
								<StepLabel>Congratulations</StepLabel>
							</Step>
						</Stepper>
						<ExpandTransition loading={loading} open={true}>
							{this.renderHorizontalContent()}
						</ExpandTransition>
					</div>
					}
					{(this.state.stepperOrientation === 'vertical') &&
					<div>
						<Stepper activeStep={stepIndex} orientation="vertical">
							<Step>
								<StepLabel>Swipe to create account</StepLabel>
								<StepContent>
									{this.getStepContent(0)}
									{this.renderStepActions(0)}
								</StepContent>
							</Step>
							<Step>
								<StepLabel>Save the Access Key</StepLabel>
								<StepContent>
									{this.getStepContent(1)}
									{this.renderStepActions(1)}
								</StepContent>
							</Step>
							<Step>
								<StepLabel>Congratulations</StepLabel>
								<StepContent>
									{this.getStepContent(2)}
									{this.renderStepActions(2)}
								</StepContent>
							</Step>
						</Stepper>
					</div>
					}
				</div>
			</div>
		);
	}
}

export default Register;
